# Generated by Django 4.0.4 on 2022-10-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_complaintrack_complain'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('open', 'open'), ('viewed', 'viewed'), ('Resolved', 'Resolved')], default='pending', max_length=30),
        ),
        migrations.DeleteModel(
            name='ComplainTrack',
        ),
    ]
