# Generated by Django 4.0 on 2022-12-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_complain_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
